//! Decodes reviewable hexadecimal corpus fixtures without changing fuzz input semantics.
//!
//! Checked-in persisted records often contain NUL bytes, which are awkward to
//! maintain as source patches. A seed prefixed with `hex:` is decoded to its
//! exact bytes; every other input is passed through unchanged, including all
//! data generated by libFuzzer.

use std::borrow::Cow;

pub(crate) fn bytes(data: &[u8]) -> Cow<'_, [u8]> {
    let Some(encoded) = data.strip_prefix(b"hex:") else {
        return Cow::Borrowed(data);
    };
    let encoded = encoded.strip_suffix(b"\n").unwrap_or(encoded);
    if encoded.len() % 2 != 0 {
        return Cow::Borrowed(data);
    }

    let mut decoded = Vec::with_capacity(encoded.len() / 2);
    for pair in encoded.chunks_exact(2) {
        let (Some(high), Some(low)) = (nibble(pair[0]), nibble(pair[1])) else {
            return Cow::Borrowed(data);
        };
        decoded.push((high << 4) | low);
    }
    Cow::Owned(decoded)
}

const fn nibble(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_seeds_decode_and_arbitrary_inputs_pass_through() {
        assert_eq!(bytes(b"hex:0006ff\n").as_ref(), &[0x00, 0x06, 0xFF]);
        assert_eq!(bytes(b"raw").as_ref(), b"raw");
        assert_eq!(bytes(b"hex:0").as_ref(), b"hex:0");
        assert_eq!(bytes(b"hex:zz").as_ref(), b"hex:zz");
    }
}
