[package]
name = "helixdb-uniffi-bindgen"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "helixdb-uniffi-bindgen-go"
path = "src/bin/go.rs"
required-features = ["go"]

[[bin]]
name = "helixdb-uniffi-bindgen-node"
path = "src/bin/node.rs"
required-features = ["node"]

[features]
default = ["go", "node"]
go = ["dep:uniffi-bindgen-go"]
node = ["dep:uniffi-bindgen-node-js"]

[dependencies]
anyhow = "1"
uniffi-bindgen-go = { git = "https://github.com/NordSecurity/uniffi-bindgen-go.git", tag = "v0.7.1+v0.31.0", version = "=0.7.1", optional = true }
uniffi-bindgen-node-js = { version = "=0.0.16", optional = true }

[workspace]
resolver = "3"
