[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { path = "../db" }
helix-ast = { path = "../ast" }
helix-metrics = { path = "../metrics" }
axum = "0.8.8"
object_store = "0.14"
prost = "0.14.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sonic-rs = "0.5.8"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
prost-build = "0.14"
protoc-bin-vendored = "3.2"
tonic-prost-build = "0.14.6"

[dev-dependencies]
async-trait = "0.1"
helix-db = { path = "../../sdks/rust" }
helix-db-testkit = { path = "../db-testkit" }
helix-planner = { path = "../planner" }
slatedb = { git = "https://github.com/HelixDB/slatedb.git", rev = "c64286ec8e5aaa724f12a8c54b58fe73efcff534" }
tokio-test = "0.4"
tokio-stream = { version = "0.1", features = ["net"] }
tower = { version = "0.5", features = ["util"] }

[lints]
workspace = true
